version: '3.7'
services:
  web:
    image: webdevops/php-apache-dev:8.0
    container_name: screens2
    restart: "no"
    user: root
    environment:
      - WEB_ALIAS_DOMAIN=screen.loc
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=4G
      - PHP_MAX_EXECUTION_TIME=18000
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - COMPOSER_VERSION=2
      - PHP_DEBUGGER=none 
    volumes:
      - ./:/app:cached
    ports:
      - "80:80"
      - "443:443"
      - "32823:22" 